//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class computadora
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Procesador { get; set; }
        public int MemoriaRam { get; set; }
        public int Almacenamiento { get; set; }
        public string SistemaOperativo { get; set; }
        public int Cantidad { get; set; }
        public int AltaStock { get; set; }
        public int BajaStock { get; set; }
    }
}
